stages:
  - test

smoke_tests:
  stage: test
  script:
    - curl -X POST ... --location "https://api.prod.autonoma.app/v1/run/folder/$SMOKE_FOLDER_ID" ...
  only:
    - merge_requests

regression_tests:
  stage: test
  script:
    - curl -X POST ... --location "https://api.prod.autonoma.app/v1/run/folder/$REGRESSION_FOLDER_ID" ...
  only:
    - main
