stages:
  - test

smoke_tests:
  stage: test
  script:
    - curl -H "Authorization: Bearer $AUTONOMA_API_TOKEN" -X POST ... --location "https://api.prod.autonoma.app/v1/run/folder/$SMOKE_FOLDER_ID" ...
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

regression_tests:
  stage: test
  script:
    - curl -X POST ... --location "https://api.prod.autonoma.app/v1/run/folder/$REGRESSION_FOLDER_ID" ...
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
