#!/bin/bash
# 📋 INFRASTRUCTURE QUICK REFERENCE
# All commands for 100% implemented infrastructure

echo "🚀 Infamous Freight Infrastructure - Quick Reference"
echo "=================================================="
echo ""

# ============================================================================
# DEVELOPMENT - Start Here
# ============================================================================
echo "📦 DEVELOPMENT ENVIRONMENT"
echo "=========================="
echo ""
echo "Start all services (auto-loads docker-compose.override.yml):"
echo "  docker-compose up -d"
echo ""
echo "Check status:"
echo "  docker-compose ps"
echo ""
echo "View logs:"
echo "  docker-compose logs -f api"
echo "  docker-compose logs -f web"
echo "  docker-compose logs -f postgres"
echo ""
echo "Stop all services:"
echo "  docker-compose down"
echo ""

# ============================================================================
# SERVICES & PORTS
# ============================================================================
echo "🔗 SERVICE ENDPOINTS"
echo "===================="
echo ""
echo "Main Services:"
echo "  API:                    http://localhost:4000"
echo "  Web:                    http://localhost:3000"
echo "  API Health:             http://localhost:4000/api/health"
echo "  API Health Dashboard:   http://localhost:4000/api/health/dashboard"
echo ""
echo "Development Tools:"
echo "  pgAdmin (DB Manager):   http://localhost:5050      (user/pass: admin/admin)"
echo "  Redis Commander:        http://localhost:8081"
echo ""
echo "Monitoring Stack (with --profile monitoring):"
echo "  Prometheus:             http://localhost:9090"
echo "  Grafana:                http://localhost:3001      (user/pass: admin/admin)"
echo ""
echo "API Documentation:"
echo "  Swagger UI:             http://localhost:4000/api/docs"
echo ""

# ============================================================================
# DOCKER COMPOSE
# ============================================================================
echo "🐳 DOCKER COMPOSE COMMANDS"
echo "=========================="
echo ""
echo "Development (all services):"
echo "  docker-compose up -d"
echo ""
echo "Production (blue-green):"
echo "  docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d"
echo ""
echo "Monitoring Stack (optional):"
echo "  docker-compose --profile monitoring up -d"
echo ""
echo "Development Tools (pgAdmin, Redis Commander):"
echo "  docker-compose --profile dev up -d"
echo ""
echo "Multiple Profiles:"
echo "  docker-compose --profile api --profile monitoring up -d"
echo ""
echo "Stop Services:"
echo "  docker-compose down                    # Keep volumes"
echo "  docker-compose down -v                 # Remove volumes"
echo ""
echo "Clean Up:"
echo "  docker system prune                    # Remove unused containers/images"
echo "  docker volume prune                    # Remove unused volumes"
echo ""

# ============================================================================
# HEALTH CHECKS
# ============================================================================
echo "🏥 HEALTH CHECKS"
echo "================"
echo ""
echo "Basic Health (uptime, services):"
echo "  curl http://localhost:4000/api/health"
echo ""
echo "Liveness Probe (Kubernetes compatible):"
echo "  curl http://localhost:4000/api/health/live"
echo ""
echo "Readiness Probe (503 if DB unavailable):"
echo "  curl http://localhost:4000/api/health/ready"
echo ""
echo "Detailed Metrics (requires token):"
echo "  curl -H \"Authorization: Bearer \$TOKEN\" http://localhost:4000/api/health/details"
echo ""
echo "Visual Dashboard (auto-refresh 30s):"
echo "  open http://localhost:4000/api/health/dashboard"
echo ""
echo "Quick Health Check Script:"
echo "  ./scripts/healthcheck.sh --once"
echo ""
echo "Continuous Monitoring (every 30s):"
echo "  ./scripts/healthcheck.sh --interval 30"
echo ""

# ============================================================================
# BLUE-GREEN DEPLOYMENT
# ============================================================================
echo "🔄 BLUE-GREEN DEPLOYMENT"
echo "========================"
echo ""
echo "Check Status:"
echo "  ./scripts/switch-deployment.sh status"
echo ""
echo "Deploy to Green (new version):"
echo "  docker-compose -f docker-compose.prod.yml up -d api-green"
echo ""
echo "Test Green Health:"
echo "  curl http://api-green:4000/api/health"
echo ""
echo "Switch Traffic to Green:"
echo "  ./scripts/switch-deployment.sh green"
echo ""
echo "Switch Back to Blue (rollback):"
echo "  ./scripts/switch-deployment.sh blue"
echo ""
echo "Health Check Both Deployments:"
echo "  ./scripts/switch-deployment.sh health-check"
echo ""

# ============================================================================
# SECRETS MANAGEMENT
# ============================================================================
echo "🔐 SECRETS MANAGEMENT"
echo "===================="
echo ""
echo "Generate Secrets:"
echo "  ./scripts/setup-secrets.sh"
echo ""
echo "Secrets Created (in ./secrets/):"
echo "  - jwt_secret.txt"
echo "  - jwt_refresh_secret.txt"
echo "  - db_password.txt"
echo "  - redis_password.txt"
echo ""
echo "Load Secrets in Code:"
echo "  const { secrets, validateSecrets } = require('./api/src/config/secrets');"
echo "  validateSecrets();"
echo "  const jwtSecret = secrets.jwtSecret;"
echo ""
echo "Docker Swarm (create secrets):"
echo "  docker secret create jwt_secret ./secrets/jwt_secret.txt"
echo ""

# ============================================================================
# MONITORING & METRICS
# ============================================================================
echo "📊 MONITORING"
echo "============="
echo ""
echo "Start Monitoring Stack:"
echo "  docker-compose --profile monitoring up -d"
echo ""
echo "Prometheus Targets:"
echo "  curl http://localhost:9090/api/v1/targets"
echo ""
echo "Query Metrics (Prometheus PromQL):"
echo "  curl 'http://localhost:9090/api/v1/query?query=http_requests_total'"
echo ""
echo "Create Grafana Dashboard:"
echo "  1. Open http://localhost:3001"
echo "  2. Login (admin/admin)"
echo "  3. Create → Dashboard → Add Panel"
echo "  4. Select Prometheus data source"
echo "  5. Query: rate(http_requests_total[5m])"
echo ""
echo "Available Metrics:"
echo "  - http_requests_total          (API request count)"
echo "  - http_request_duration_ms     (Response time)"
echo "  - node_cpu_seconds_total       (System CPU)"
echo "  - node_memory_MemAvailable     (System memory)"
echo "  - pg_stat_activity_count       (DB connections)"
echo "  - redis_memory_used_bytes      (Redis memory)"
echo ""

# ============================================================================
# CONTAINER MANAGEMENT
# ============================================================================
echo "📦 CONTAINER MANAGEMENT"
echo "======================="
echo ""
echo "List Services:"
echo "  docker-compose ps"
echo ""
echo "View Service Logs:"
echo "  docker-compose logs -f api"
echo "  docker-compose logs -f postgres"
echo ""
echo "Execute Commands in Container:"
echo "  docker-compose exec postgres psql -U postgres"
echo "  docker-compose exec redis redis-cli"
echo ""
echo "Resource Usage:"
echo "  docker stats"
echo ""
echo "Restart Service:"
echo "  docker-compose restart api"
echo ""
echo "Remove Service (keep volume):"
echo "  docker-compose rm -f api"
echo ""
echo "Rebuild Image:"
echo "  docker-compose build api"
echo "  docker-compose build api --no-cache"
echo ""

# ============================================================================
# DATABASE MANAGEMENT
# ============================================================================
echo "🗄️ DATABASE (PostgreSQL)"
echo "========================"
echo ""
echo "Connect to Database:"
echo "  docker-compose exec postgres psql -U postgres -d infamous_freight"
echo ""
echo "Common Commands:"
echo "  \\dt                           (list tables)"
echo "  \\d table_name                 (describe table)"
echo "  SELECT version();              (show version)"
echo "  SELECT COUNT(*) FROM table;    (count rows)"
echo ""
echo "Backup Database:"
echo "  docker-compose exec postgres pg_dump -U postgres -d infamous_freight > backup.sql"
echo ""
echo "Restore Database:"
echo "  docker-compose exec -T postgres psql -U postgres -d infamous_freight < backup.sql"
echo ""
echo "pgAdmin (GUI):"
echo "  open http://localhost:5050"
echo "  User: admin@infamous.local"
echo "  Pass: admin"
echo ""

# ============================================================================
# REDIS CACHE
# ============================================================================
echo "💾 REDIS CACHE"
echo "=============="
echo ""
echo "Connect to Redis:"
echo "  docker-compose exec redis redis-cli"
echo ""
echo "Common Commands (in redis-cli):"
echo "  ping                          (test connection)"
echo "  info                          (server info)"
echo "  dbsize                        (key count)"
echo "  keys *                        (list all keys)"
echo "  get key_name                  (get value)"
echo "  flushall                      (clear all)"
echo ""
echo "Redis Commander (GUI):"
echo "  open http://localhost:8081"
echo ""

# ============================================================================
# SECURITY SCANNING
# ============================================================================
echo "🛡️ SECURITY"
echo "============"
echo ""
echo "Run Security Scans Locally:"
echo "  npm audit --audit-level=moderate"
echo "  npx trivy image ghcr.io/infamous-freight-enterprises/api:latest"
echo ""
echo "GitHub Security Checks:"
echo "  - npm audit (on PR, blocking critical)"
echo "  - Trivy container scanning (post-build)"
echo "  - CodeQL analysis (JavaScript/TypeScript)"
echo "  - pnpm outdated (dependency monitoring)"
echo ""
echo "View Results:"
echo "  1. Go to GitHub repo → Security tab"
echo "  2. View Code scanning alerts"
echo "  3. View Dependabot alerts"
echo ""

# ============================================================================
# CI/CD & IMAGE REGISTRY
# ============================================================================
echo "🔨 CI/CD & REGISTRY"
echo "==================="
echo ""
echo "GitHub Container Registry (GHCR):"
echo "  docker login ghcr.io"
echo "  # Use personal access token (PAT) as password"
echo ""
echo "Pull Image:"
echo "  docker pull ghcr.io/infamous-freight-enterprises/api:main"
echo ""
echo "Push Image:"
echo "  docker tag local-image ghcr.io/infamous-freight-enterprises/api:v1.0.0"
echo "  docker push ghcr.io/infamous-freight-enterprises/api:v1.0.0"
echo ""
echo "Image Tags:"
echo "  latest              (most recent)"
echo "  main                (main branch)"
echo "  v1.2.3              (version tag)"
echo "  sha-a1b2c3d        (git SHA)"
echo ""
echo "CI/CD Workflows:"
echo "  - docker-build-push.yml       (build & push on push)"
echo "  - security-scan.yml           (weekly security audits)"
echo ""

# ============================================================================
# TROUBLESHOOTING
# ============================================================================
echo "🔧 TROUBLESHOOTING"
echo "=================="
echo ""
echo "Port Already in Use:"
echo "  lsof -ti:4000 | xargs kill -9      # Kill process on port 4000"
echo "  lsof -ti:5432 | xargs kill -9      # Kill process on port 5432"
echo ""
echo "Health Check Failing:"
echo "  docker-compose logs api            # Check API logs"
echo "  docker-compose logs postgres       # Check DB logs"
echo ""
echo "Database Connection Issues:"
echo "  docker-compose exec postgres psql -U postgres -c \"SELECT 1\""
echo ""
echo "Redis Connection Issues:"
echo "  docker-compose exec redis redis-cli ping"
echo ""
echo "Rebuild & Restart:"
echo "  docker-compose down -v"
echo "  docker-compose build --no-cache"
echo "  docker-compose up -d"
echo ""
echo "Check Volumes:"
echo "  docker volume ls"
echo "  docker volume inspect volume_name"
echo ""

# ============================================================================
# USEFUL LINKS
# ============================================================================
echo "📚 DOCUMENTATION & LINKS"
echo "======================="
echo ""
echo "Implementation Guide:"
echo "  100_PERCENT_IMPLEMENTATION_GUIDE.md"
echo ""
echo "Task Checklist:"
echo "  100_PERCENT_IMPLEMENTATION_CHECKLIST.md"
echo ""
echo "Infrastructure Recommendations:"
echo "  INFRASTRUCTURE_RECOMMENDATIONS_2026.md"
echo ""
echo "API Documentation:"
echo "  http://localhost:4000/api/docs"
echo ""
echo "GitHub Repository:"
echo "  https://github.com/santorio-miles/infamous-freight-enterprises"
echo ""

# ============================================================================
# QUICK SETUP WIZARD
# ============================================================================
echo "⚡ QUICK SETUP (Copy & Paste)"
echo "============================="
echo ""
echo "1️⃣  Development Environment:"
echo "    docker-compose up -d"
echo "    sleep 5"
echo "    curl http://localhost:4000/api/health"
echo ""
echo "2️⃣  Generate Secrets:"
echo "    ./scripts/setup-secrets.sh"
echo ""
echo "3️⃣  Production Setup:"
echo "    docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d"
echo ""
echo "4️⃣  Start Monitoring:"
echo "    docker-compose --profile monitoring up -d"
echo ""
echo "5️⃣  Health Check:"
echo "    ./scripts/healthcheck.sh --once"
echo ""

echo ""
echo "✅ Infrastructure 100% Ready!"
echo "=================================================="
