apiVersion: v1
kind: ServiceAccount
metadata:
  name: infamous-freight-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infamous-freight-api
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infamous-freight-api
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infamous-freight-api
subjects:
  - kind: ServiceAccount
    name: infamous-freight-api
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infamous-freight-backup
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infamous-freight-backup
  namespace: default
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infamous-freight-backup
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infamous-freight-backup
subjects:
  - kind: ServiceAccount
    name: infamous-freight-backup
    namespace: default
