blank_issues_enabled: false

contact_links:
  - name: Security Vulnerility
    url: https://github.com/Infamous-freight-enterprises/.github/security/policy
    about: Please review the security policy for reporting vulnerabilities.
