import { env } from "./config/env.js";

export const ENV = {
  DATABASE_URL: env.databaseUrl,
  JWT_SECRET: env.jwtSecret,
  JWT_ALGORITHM: env.jwtAlgorithm,
  JWT_PRIVATE_KEY: env.jwtPrivateKey,
  JWT_PUBLIC_KEY: env.jwtPublicKey,
  JWT_ACCESS_EXPIRES_IN: env.jwtAccessExpiresIn,
  JWT_REFRESH_EXPIRES_IN: env.jwtRefreshExpiresIn,
  JWT_ISSUER: env.jwtIssuer,
  JWT_AUDIENCE: env.jwtAudience,
  APP_PORT: env.appPort,
  API_PORT: env.appPort,
  PORT: env.appPort,
  CORS_ORIGIN: env.corsOrigin,
  AUTH_COOKIE_ENABLED: env.authCookieEnabled,
  AUTH_COOKIE_NAME: env.authCookieName,
  AUTH_COOKIE_DOMAIN: env.authCookieDomain,
  AUTH_COOKIE_SECURE: env.authCookieSecure,
  AUTH_COOKIE_SAME_SITE: env.authCookieSameSite,
  AUTH_COOKIE_PATH: env.authCookiePath,
  ARGON2_MEMORY_COST: env.argon2.memoryCost,
  ARGON2_TIME_COST: env.argon2.timeCost,
  ARGON2_PARALLELISM: env.argon2.parallelism,
};
