#!/bin/bash
# Quick Start Script - Get everything running in 5 minutes
# Infamous Freight Enterprises

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

clear
echo -e "${BLUE}${BOLD}"
cat << "EOF"
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║        ██╗███╗   ██╗███████╗ █████╗ ███╗   ███╗ ██████╗      ║
║        ██║████╗  ██║██╔════╝██╔══██╗████╗ ████║██╔═══██╗     ║
║        ██║██╔██╗ ██║█████╗  ███████║██╔████╔██║██║   ██║     ║
║        ██║██║╚██╗██║██╔══╝  ██╔══██║██║╚██╔╝██║██║   ██║     ║
║        ██║██║ ╚████║██║     ██║  ██║██║ ╚═╝ ██║╚██████╔╝     ║
║        ╚═╝╚═╝  ╚═══╝╚═╝     ╚═╝  ╚═╝╚═╝     ╚═╝ ╚═════╝      ║
║                                                               ║
║             Infamous Freight Enterprises                      ║
║                 Quick Start Script                            ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"
echo ""
echo -e "${YELLOW}This script will:${NC}"
echo "  1. ✓ Install dependencies"
echo "  2. ✓ Build shared package"
echo "  3. ✓ Setup environment"
echo "  4. ✓ Start development server"
echo ""
read -p "Press Enter to continue..."
echo ""

# Change to project root
cd /workspaces/Infamous-freight-enterprises

# Step 1: Install dependencies
echo -e "${BLUE}═══ Step 1/4: Installing Dependencies ═══${NC}"
if pnpm install; then
  echo -e "${GREEN}✓ Dependencies installed${NC}"
else
  echo -e "${RED}✗ Failed to install dependencies${NC}"
  exit 1
fi
echo ""

# Step 2: Build shared package
echo -e "${BLUE}═══ Step 2/4: Building Shared Package ═══${NC}"
if pnpm --filter @infamous-freight/shared build; then
  echo -e "${GREEN}✓ Shared package built${NC}"
else
  echo -e "${RED}✗ Failed to build shared package${NC}"
  exit 1
fi
echo ""

# Step 3: Setup environment
echo -e "${BLUE}═══ Step 3/4: Setting Up Environment ═══${NC}"

# Check if .env.local exists
if [ ! -f "apps/web/.env.local" ]; then
  echo -e "${YELLOW}Creating apps/web/.env.local from template...${NC}"
  
  cat > apps/web/.env.local <<EOF
# Development Environment Variables
# Auto-generated by quick-start.sh on $(date)

# Supabase Configuration (Mock mode - set real values for production)
NEXT_PUBLIC_SUPABASE_URL=https://mock.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=mock-key

# Development Settings
NODE_ENV=development
NEXT_PUBLIC_ENV=development
EOF
  
  echo -e "${GREEN}✓ Environment file created${NC}"
  echo -e "${YELLOW}⚠ Using mock Supabase - set up real Supabase for full features${NC}"
  echo -e "${BLUE}  Run: ./scripts/setup-supabase-cloud.sh${NC}"
else
  echo -e "${GREEN}✓ Environment file already exists${NC}"
fi
echo ""

# Step 4: Start development server
echo -e "${BLUE}═══ Step 4/4: Starting Development Server ═══${NC}"
echo ""
echo -e "${YELLOW}Select which to start:${NC}"
echo "  1) Web app only (Port 3000)"
echo "  2) All services (Web + API)"
echo "  3) Skip (I'll start manually)"
echo ""
read -p "Choice (1-3): " START_CHOICE

case $START_CHOICE in
  1)
    echo ""
    echo -e "${GREEN}Starting web app...${NC}"
    echo -e "${BLUE}Access at: ${BOLD}http://localhost:3000${NC}"
    echo ""
    echo -e "${YELLOW}Press Ctrl+C to stop${NC}"
    echo ""
    cd apps/web
    pnpm dev
    ;;
  2)
    echo ""
    echo -e "${GREEN}Starting all services...${NC}"
    echo -e "${BLUE}Web:  ${BOLD}http://localhost:3000${NC}"
    echo -e "${BLUE}API:  ${BOLD}http://localhost:4000${NC}"
    echo ""
    echo -e "${YELLOW}Press Ctrl+C to stop${NC}"
    echo ""
    pnpm dev
    ;;
  3)
    echo ""
    echo -e "${GREEN}✓ Setup complete!${NC}"
    ;;
  *)
    echo -e "${RED}Invalid choice${NC}"
    exit 1
    ;;
esac

# If user chose skip, show next steps
if [ "$START_CHOICE" = "3" ]; then
  echo ""
  echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
  echo -e "${GREEN}${BOLD}   Setup Complete!${NC}"
  echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
  echo ""
  echo -e "${YELLOW}Next steps:${NC}"
  echo ""
  echo -e "${BOLD}1. Start development:${NC}"
  echo "   ${BLUE}cd apps/web && pnpm dev${NC}              # Web app only"
  echo "   ${BLUE}pnpm dev${NC}                             # All services"
  echo ""
  echo -e "${BOLD}2. Set up Supabase (optional):${NC}"
  echo "   ${BLUE}./scripts/setup-supabase-cloud.sh${NC}   # Automated setup"
  echo "   ${BLUE}See: docs/SUPABASE_CLOUD_SETUP.md${NC}   # Manual setup"
  echo ""
  echo -e "${BOLD}3. Run tests:${NC}"
  echo "   ${BLUE}pnpm test${NC}                           # All tests"
  echo "   ${BLUE}pnpm --filter api test:coverage${NC}     # API coverage"
  echo ""
  echo -e "${BOLD}4. Validate everything:${NC}"
  echo "   ${BLUE}./scripts/validate-all.sh${NC}           # Full validation"
  echo ""
  echo -e "${BOLD}5. Deploy to production:${NC}"
  echo "   ${BLUE}./scripts/deploy-production.sh${NC}      # Deployment wizard"
  echo ""
  echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
  echo -e "${GREEN}Documentation:${NC}"
  echo "   • ${BLUE}README.md${NC}                         - Project overview"
  echo "   • ${BLUE}QUICK_REFERENCE.md${NC}                - Command reference"
  echo "   • ${BLUE}SUPABASE_100_COMPLETE.md${NC}          - Supabase guide"
  echo "   • ${BLUE}docs/SUPABASE_CLOUD_SETUP.md${NC}      - Cloud setup"
  echo ""
  echo -e "${YELLOW}Need help?${NC}"
  echo "   • GitHub: ${BLUE}https://github.com/MrMiless44/Infamous-freight${NC}"
  echo "   • Issues: ${BLUE}https://github.com/MrMiless44/Infamous-freight/issues${NC}"
  echo ""
  echo -e "${GREEN}Happy coding! 🚀${NC}"
  echo ""
fi
