#!/bin/bash
# Supabase Cloud Setup Automation Script
# This script automates the setup of Supabase Cloud for the Infamous Freight Enterprises project

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}   Infamous Freight Enterprises - Supabase Cloud Setup${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo -e "${YELLOW}Supabase CLI not found. Installing...${NC}"
    npm install -g supabase
fi

# Check if user is logged in
echo -e "${BLUE}Step 1: Login to Supabase${NC}"
if ! supabase status &> /dev/null; then
    echo -e "${YELLOW}Logging in to Supabase...${NC}"
    supabase login
fi

# Get project reference from user
echo ""
echo -e "${BLUE}Step 2: Link to Supabase Project${NC}"
echo -e "${YELLOW}Please enter your Supabase project reference ID:${NC}"
echo -e "${YELLOW}(Find this in your Supabase dashboard: Settings > General > Reference ID)${NC}"
read -p "Project Reference ID: " PROJECT_REF

if [ -z "$PROJECT_REF" ]; then
    echo -e "${RED}Error: Project reference ID cannot be empty${NC}"
    exit 1
fi

# Link to project
echo -e "${GREEN}Linking to project: $PROJECT_REF${NC}"
supabase link --project-ref "$PROJECT_REF"

# Push database migrations
echo ""
echo -e "${BLUE}Step 3: Push Database Migrations${NC}"
echo -e "${YELLOW}This will apply all migrations to your Supabase database...${NC}"
read -p "Continue? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cd /workspaces/Infamous-freight-enterprises
    supabase db push
    echo -e "${GREEN}✓ Database migrations applied successfully${NC}"
else
    echo -e "${YELLOW}Skipping database migrations${NC}"
fi

# Deploy Edge Functions
echo ""
echo -e "${BLUE}Step 4: Deploy Edge Functions${NC}"
echo -e "${YELLOW}Deploying Edge Functions: analytics, shipment-tracking${NC}"
read -p "Continue? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cd /workspaces/Infamous-freight-enterprises
    
    # Deploy each function
    echo -e "${GREEN}Deploying analytics function...${NC}"
    supabase functions deploy analytics --no-verify-jwt
    
    echo -e "${GREEN}Deploying shipment-tracking function...${NC}"
    supabase functions deploy shipment-tracking --no-verify-jwt
    
    echo -e "${GREEN}✓ Edge Functions deployed successfully${NC}"
else
    echo -e "${YELLOW}Skipping Edge Functions deployment${NC}"
fi

# Get API credentials
echo ""
echo -e "${BLUE}Step 5: Configure Environment Variables${NC}"
echo -e "${YELLOW}Getting project credentials...${NC}"

# Get project details
PROJECT_URL=$(supabase status | grep "API URL" | awk '{print $3}')
ANON_KEY=$(supabase status | grep "anon key" | awk '{print $3}')
SERVICE_ROLE_KEY=$(supabase status | grep "service_role key" | awk '{print $3}')

if [ -z "$PROJECT_URL" ] || [ -z "$ANON_KEY" ]; then
    echo -e "${YELLOW}Could not auto-retrieve credentials. Please get them manually:${NC}"
    echo -e "${YELLOW}1. Go to: https://supabase.com/dashboard/project/$PROJECT_REF/settings/api${NC}"
    echo -e "${YELLOW}2. Copy Project URL and anon key${NC}"
    echo ""
    read -p "Project URL: " PROJECT_URL
    read -p "Anon Key: " ANON_KEY
    read -p "Service Role Key (optional): " SERVICE_ROLE_KEY
fi

# Create .env.local file for web app
WEB_ENV_FILE="/workspaces/Infamous-freight-enterprises/apps/web/.env.local"
echo -e "${GREEN}Creating environment file: $WEB_ENV_FILE${NC}"

cat > "$WEB_ENV_FILE" <<EOF
# Supabase Configuration (Auto-generated by setup-supabase-cloud.sh)
# Generated on: $(date)

# Public Supabase Configuration
NEXT_PUBLIC_SUPABASE_URL=$PROJECT_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY

# Server-side Supabase Configuration (KEEP SECRET)
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY

# Supabase Project Reference
SUPABASE_PROJECT_REF=$PROJECT_REF
EOF

echo -e "${GREEN}✓ Environment file created successfully${NC}"

# Generate TypeScript types
echo ""
echo -e "${BLUE}Step 6: Generate TypeScript Types${NC}"
read -p "Generate TypeScript types from database? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    cd /workspaces/Infamous-freight-enterprises
    mkdir -p apps/web/types
    supabase gen types typescript --linked > apps/web/src/types/database.ts
    echo -e "${GREEN}✓ TypeScript types generated${NC}"
else
    echo -e "${YELLOW}Skipping TypeScript type generation${NC}"
fi

# Summary
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}   ✓ Supabase Cloud Setup Complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}Next Steps:${NC}"
echo -e "  1. Restart your web app: ${YELLOW}cd apps/web && pnpm dev${NC}"
echo -e "  2. Test authentication and database queries"
echo -e "  3. Configure production environment variables in Vercel/Netlify"
echo ""
echo -e "${GREEN}Environment Variables Created:${NC}"
echo -e "  File: ${YELLOW}$WEB_ENV_FILE${NC}"
echo -e "  Project URL: ${YELLOW}$PROJECT_URL${NC}"
echo -e "  Project Ref: ${YELLOW}$PROJECT_REF${NC}"
echo ""
echo -e "${YELLOW}⚠ Important:${NC}"
echo -e "  - Keep ${YELLOW}SUPABASE_SERVICE_ROLE_KEY${NC} secret (server-side only)"
echo -e "  - Add ${YELLOW}.env.local${NC} to .gitignore (already done)"
echo -e "  - Update production environment variables before deploying"
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
