functionsDirectory = "/opt/build/repo/apps/web/.netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[dev]
command = "pnpm --filter web dev"
port = 8888.0
targetPort = 3000.0
autoLaunch = false

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "/opt/build/repo/apps/web/.next"
publishOrigin = "config"
commandOrigin = "config"
command = "pnpm install --frozen-lockfile && pnpm --filter web build"
base = "/opt/build/repo"
functions = "/opt/build/repo/apps/web/.netlify/functions"

[build.environment]
NODE_VERSION = "24"
PNPM_VERSION = "10.15.0"
NEXT_TELEMETRY_DISABLED = "1"
BUILD_TARGET = "netlify"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]