name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Validate repo standards
        run: echo "Validating standards..."

      - name: Run fly-config test
        run: bash tests/ci/fly-config.test.sh

      - name: Run other jobs
        run: echo "Executing other jobs..."
