name: Deploy ALL Platforms

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - "ai/**"
      - "src/apps/mobile/**"
      - "packages/**"
      - "pnpm-lock.yaml"
      - "infrastructure/**"
      - "docs/**"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: deploy-all
  cancel-in-progress: false

jobs:
  deploy-api:
    uses: ./.github/workflows/deploy-api.yml
    secrets: inherit

  deploy-mobile:
    uses: ./.github/workflows/deploy-mobile.yml
    secrets: inherit
