name: Deploy ALL Platforms

on:
  workflow_dispatch:

concurrency:
  group: deploy-all
  cancel-in-progress: false

jobs:
  deploy-api:
    uses: ./.github/workflows/deploy-api.yml
    secrets: inherit

  deploy-mobile:
    uses: ./.github/workflows/deploy-mobile.yml
    secrets: inherit
